export const demoProjects = [
  {
    id: '1',
    title: 'Eco-Friendly Delivery App',
    description: 'A green logistics solution for sustainable urban deliveries.',
    image: 'https://images.unsplash.com/photo-1586880244406-556ebe35f282?w=800&auto=format&fit=crop&q=60',
    category: ['Mobile Apps'],
    technologies: ['Flutter', 'Firebase'],
  },
  {
    id: '2',
    title: 'Neural Network Visualizer',
    description: 'An interactive tool for visualizing and understanding neural networks.',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop&q=60',
    category: ['AI/ML'],
    technologies: ['Python', 'React'],
  },
  {
    id: '3',
    title: 'Crypto Trading Bot',
    description: 'An automated cryptocurrency trading system using advanced algorithms.',
    image: 'https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=800&auto=format&fit=crop&q=60',
    category: ['AI/ML'],
    technologies: ['Python', 'Node.js'],
  },
  {
    id: '4',
    title: 'VR Fitness Trainer',
    description: 'A virtual reality application for immersive fitness experiences.',
    image: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&auto=format&fit=crop&q=60',
    category: ['Mobile Apps'],
    technologies: ['Unity', 'C#'],
  },
  {
    id: '5',
    title: 'AI Music Composer',
    description: 'An AI-powered tool for generating original music compositions.',
    image: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800&auto=format&fit=crop&q=60',
    category: ['AI/ML'],
    technologies: ['Python', 'TensorFlow'],
  },
  {
    id: '6',
    title: 'Real-Time Translator',
    description: 'A mobile app for instant translation of spoken languages.',
    image: 'https://images.unsplash.com/photo-1523287562758-66c7fc58967f?w=800&auto=format&fit=crop&q=60',
    category: ['Mobile Apps'],
    technologies: ['Flutter', 'Firebase'],
  },
  {
    id: '7',
    title: 'Smart Home Assistant',
    description: 'IoT-based home automation system with voice control.',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=60',
    category: ['IoT'],
    technologies: ['Raspberry Pi', 'Python'],
  },
  {
    id: '8',
    title: 'E-Commerce Platform',
    description: 'Full-stack web application for online retail.',
    image: 'https://images.unsplash.com/photo-1557821552-17105176677c?w=800&auto=format&fit=crop&q=60',
    category: ['Web Development'],
    technologies: ['React', 'Node.js'],
  },
  {
    id: '9',
    title: 'Weather Prediction Model',
    description: 'ML-based weather forecasting system.',
    image: 'https://images.unsplash.com/photo-1526761122248-c31c93f8b2b9?w=800&auto=format&fit=crop&q=60',
    category: ['AI/ML'],
    technologies: ['Python', 'Scikit-learn'],
  },
  {
    id: '10',
    title: 'Social Media Dashboard',
    description: 'Analytics platform for social media management.',
    image: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&auto=format&fit=crop&q=60',
    category: ['Web Development'],
    technologies: ['Vue.js', 'Express'],
  },
  {
    id: '11',
    title: 'Plant Disease Detector',
    description: 'Mobile app using AI to identify plant diseases.',
    image: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800&auto=format&fit=crop&q=60',
    category: ['AI/ML', 'Mobile Apps'],
    technologies: ['TensorFlow', 'React Native'],
  },
  {
    id: '12',
    title: 'Smart Parking System',
    description: 'IoT solution for efficient parking management.',
    image: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800&auto=format&fit=crop&q=60',
    category: ['IoT'],
    technologies: ['Arduino', 'React'],
  },
  {
    id: '13',
    title: 'AR Navigation App',
    description: 'Augmented reality based indoor navigation system.',
    image: 'https://images.unsplash.com/photo-1527168027773-0cc890c4f42e?w=800&auto=format&fit=crop&q=60',
    category: ['Mobile Apps'],
    technologies: ['ARKit', 'Swift'],
  },
  {
    id: '14',
    title: 'Healthcare Analytics Platform',
    description: 'Data analytics solution for healthcare providers.',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=60',
    category: ['Web Development'],
    technologies: ['Angular', 'Python'],
  },
  {
    id: '15',
    title: 'Smart Energy Monitor',
    description: 'IoT device for monitoring home energy consumption.',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&auto=format&fit=crop&q=60',
    category: ['IoT'],
    technologies: ['ESP32', 'Node.js'],
  },
  {
    id: '16',
    title: 'Learning Management System',
    description: 'Web-based platform for online education.',
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=60',
    category: ['Web Development'],
    technologies: ['Django', 'React'],
  },
  ]
  
  export const featuredProject = {
    id: 'featured',
    title: 'AI-Powered Smart City Solution',
    description: 'An innovative project leveraging AI to optimize urban infrastructure.',
    longDescription: 'An innovative project leveraging AI and IoT to optimize urban infrastructure and improve city living. This comprehensive solution includes traffic management, energy optimization, and waste management systems.',
    image: 'https://images.unsplash.com/photo-1523287562758-66c7fc58967f?w=800&auto=format&fit=crop&q=60',
    category: ['AI/ML', 'IoT'],
    technologies: ['Python', 'TensorFlow', 'React'],
    featured: true,
  }
  
  export const categories = [
    "All",
    "Web Development",
    "Mobile Apps",
    "AI/ML",
    "IoT",
  ]
  
  